### ISSUE TITLE
IO Bug

### ISSUE THREAD

**Issue by HiPriv228** [PixelTech-Inc/PlotOS#7] opened 2022-01-30 17:32 UTC
Hi, please fix the bug
![image](https://user-images.githubusercontent.com/75212472/151710433-d16592b6-1781-4875-9018-faeb611adc88.png)

**Comment by BomberPlayz** [comment] 2022-02-23 18:51
Hi, sorry for not responding earlier, this project was kind of dead but development is going to resume. Would you be able to provide what actions did you do for this bug to happen? Did it happen on boot?

**Comment by BomberPlayz** [comment] 2022-04-01 18:57
I was unable to reproduce it, it may have been fixed without my knowledge.

**Closed by BomberPlayz** 2022-04-01 18:57 UTC
Labels: bug, question, can't reproduce
